import fs from "node:fs";
import path from "node:path";
import type { ApiContract } from "../types.js";
import { toStudly, toSnake, ensureDir } from "../utils.js";

function inferResources(contract: ApiContract): string[] {
  const seen = new Set<string>();
  for (const ep of contract.endpoints) {
    const name = ep.tags?.[0] ? toStudly(ep.tags[0]) : toStudly(ep.operationId);
    if (name) seen.add(name);
  }
  return [...seen];
}

// ─── Laravel Artisan Command ──────────────────────────────────────────────────

function laravelCommand(resource: string): string {
  const snake = toSnake(resource);
  return `<?php

namespace App\\Console\\Commands\\Generated;

use Illuminate\\Console\\Command;

class Process${resource}Command extends Command
{
    protected $signature = '${snake}:process {id : The ${resource} ID}';

    protected $description = 'Process a ${resource} resource';

    public function handle(): int
    {
        $id = (int) $this->argument('id');

        $this->info("Processing ${resource} #{$id}...");

        // TODO: implement processing logic
        // Example: \\App\\Jobs\\Generated\\Process${resource}Job::dispatch($id);

        $this->info('Done.');

        return self::SUCCESS;
    }
}
`;
}

function laravelCommandKernel(resources: string[]): string {
  const commands = resources
    .map((r) => `        \\App\\Console\\Commands\\Generated\\Process${r}Command::class,`)
    .join("\n");

  return `<?php

/**
 * Console Kernel registration hint — generated by BackendBridge.
 * Add the entries below to your app/Console/Kernel.php → \$commands array.
 */

// protected $commands = [
${commands}
// ];
`;
}

export function generateLaravelCommands(contract: ApiContract, outPath: string): string[] {
  const resources = inferResources(contract);
  const generated: string[] = [];
  const dir = path.join(outPath, "app", "Console", "Commands", "Generated");
  ensureDir(dir);

  for (const resource of resources) {
    const filePath = path.join(dir, `Process${resource}Command.php`);
    fs.writeFileSync(filePath, laravelCommand(resource), "utf8");
    generated.push(filePath);
  }

  const kernelHintPath = path.join(outPath, "app", "Console", "kernel.generated.php");
  fs.writeFileSync(kernelHintPath, laravelCommandKernel(resources), "utf8");
  generated.push(kernelHintPath);

  return generated;
}

// ─── Symfony Console Command ──────────────────────────────────────────────────

function symfonyCommand(resource: string): string {
  const snake = toSnake(resource);
  return `<?php

namespace App\\Command\\Generated;

use Symfony\\Component\\Console\\Attribute\\AsCommand;
use Symfony\\Component\\Console\\Command\\Command;
use Symfony\\Component\\Console\\Input\\InputArgument;
use Symfony\\Component\\Console\\Input\\InputInterface;
use Symfony\\Component\\Console\\Output\\OutputInterface;
use Symfony\\Component\\Console\\Style\\SymfonyStyle;

#[AsCommand(
    name: 'app:${snake}:process',
    description: 'Process a ${resource} resource',
)]
class Process${resource}Command extends Command
{
    protected function configure(): void
    {
        $this->addArgument('id', InputArgument::REQUIRED, 'The ${resource} ID');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $id = (int) $input->getArgument('id');

        $io->title('Processing ${resource} #' . $id);

        // TODO: inject and call your service
        // Example: $this->bus->dispatch(new \\App\\Message\\Generated\\${resource}Message($id, 'process'));

        $io->success('Done.');

        return Command::SUCCESS;
    }
}
`;
}

export function generateSymfonyCommands(contract: ApiContract, outPath: string): string[] {
  const resources = inferResources(contract);
  const generated: string[] = [];
  const dir = path.join(outPath, "src", "Command", "Generated");
  ensureDir(dir);

  for (const resource of resources) {
    const filePath = path.join(dir, `Process${resource}Command.php`);
    fs.writeFileSync(filePath, symfonyCommand(resource), "utf8");
    generated.push(filePath);
  }

  return generated;
}
