import fs from "node:fs";
import path from "node:path";
import { resolveRule, type MappingDocument } from "../mapping.js";
import type { ApiContract, EndpointContract, EndpointSchema } from "../types.js";
import { toStudly, ensureDir } from "../utils.js";

// ─── Schema → Laravel validation rules ───────────────────────────────────────

function schemaPropertyToRules(name: string, prop: EndpointSchema["properties"][string], required: boolean): string {
  const rules: string[] = [];
  if (required) rules.push("required"); else rules.push("sometimes");
  if (prop.nullable) rules.push("nullable");

  const type = prop.type ?? "string";
  if (type === "integer") rules.push("integer");
  else if (type === "number") rules.push("numeric");
  else if (type === "boolean") rules.push("boolean");
  else if (type === "array") rules.push("array");
  else rules.push("string");

  if (prop.format === "email") rules.push("email");
  else if (prop.format === "uri") rules.push("url");
  else if (prop.format === "date") rules.push("date");
  else if (prop.format === "uuid") rules.push("uuid");

  if (prop.minLength !== undefined) rules.push(`min:${prop.minLength}`);
  if (prop.maxLength !== undefined) rules.push(`max:${prop.maxLength}`);
  if (prop.minimum !== undefined) rules.push(`min:${prop.minimum}`);
  if (prop.maximum !== undefined) rules.push(`max:${prop.maximum}`);
  if (prop.enum?.length) rules.push(`in:${prop.enum.join(",")}`);

  return `            '${name}' => '${rules.join("|")}',`;
}

function generateFormRequestClass(
  className: string,
  schema: EndpointSchema,
): string {
  const rulesLines = Object.entries(schema.properties).map(([field, prop]) => {
    const isRequired = schema.required?.includes(field) ?? false;
    return schemaPropertyToRules(field, prop, isRequired);
  });

  return `<?php

namespace App\\Http\\Requests\\Generated;

use Illuminate\\Foundation\\Http\\FormRequest;

class ${className} extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
${rulesLines.join("\n")}
        ];
    }
}
`;
}

// ─── Controller generator ─────────────────────────────────────────────────────

function buildControllerBody(endpoint: EndpointContract, formRequestClass: string | null, rule: ReturnType<typeof resolveRule>): string {
  const authHint = rule?.auth?.length
    ? `        // Auth: ${rule.auth.join(", ")}\n        // $this->authorize('view', $model);\n`
    : "";

  const requestParam = formRequestClass
    ? `${formRequestClass} $request`
    : `Request $request`;

  const pathParams = (endpoint.pathParameters ?? [])
    .filter((p) => p.in === "path")
    .map((p) => `        // Path param: $${p.name} (${p.schema?.type ?? "string"})`)
    .join("\n");

  return `    public function __invoke(${requestParam}): JsonResponse
    {
${authHint}${pathParams ? pathParams + "\n" : ""}
        return response()->json([
            'status' => 'ok',
            'operation' => '${endpoint.operationId}',
        ]);
    }`;
}

function generateControllerClass(
  className: string,
  endpoint: EndpointContract,
  formRequestClass: string | null,
  rule: ReturnType<typeof resolveRule>,
): string {
  const summaryLine = endpoint.summary ? ` * ${endpoint.summary}\n` : "";
  const mappingHints = [
    rule?.dto ? ` * DTO: ${rule.dto}` : undefined,
    rule?.validation?.length ? ` * Validation: ${rule.validation.join(", ")}` : undefined,
    rule?.auth?.length ? ` * Auth: ${rule.auth.join(", ")}` : undefined,
    rule?.notes ? ` * Notes: ${rule.notes}` : undefined,
  ].filter(Boolean).join("\n");

  const requestImport = formRequestClass
    ? `use App\\Http\\Requests\\Generated\\${formRequestClass};\n`
    : "";

  return `<?php

namespace App\\Http\\Controllers\\Generated;

use App\\Http\\Controllers\\Controller;
use Illuminate\\Http\\JsonResponse;
${formRequestClass ? "" : "use Illuminate\\Http\\Request;\n"}${requestImport}
class ${className} extends Controller
{
    /**
${summaryLine}     * Auto-generated by BackendBridge.
${mappingHints ? mappingHints + "\n" : ""}     */
${buildControllerBody(endpoint, formRequestClass, rule)}
}
`;
}

// ─── Main generator ───────────────────────────────────────────────────────────

export function generateLaravelFromContract(
  contract: ApiContract,
  outPath: string,
  mapping?: MappingDocument,
): string[] {
  const generatedFiles: string[] = [];
  const controllersDir = path.join(outPath, "app", "Http", "Controllers", "Generated");
  const requestsDir = path.join(outPath, "app", "Http", "Requests", "Generated");
  const routesDir = path.join(outPath, "routes");

  ensureDir(controllersDir);
  ensureDir(routesDir);

  const routeLines: string[] = [
    "<?php",
    "",
    "use Illuminate\\Support\\Facades\\Route;",
    "",
  ];

  for (const endpoint of contract.endpoints) {
    const className = `${toStudly(endpoint.operationId)}Controller`;
    const rule = resolveRule(mapping, endpoint.method, endpoint.path, endpoint.operationId);

    // Generate FormRequest if there is a requestBody schema
    let formRequestClass: string | null = null;
    const bodySchema = endpoint.requestBodySchema;
    if (bodySchema && Object.keys(bodySchema.properties).length > 0 && ["post", "put", "patch"].includes(endpoint.method)) {
      formRequestClass = `${toStudly(endpoint.operationId)}Request`;
      const requestContent = generateFormRequestClass(formRequestClass, bodySchema);
      const requestPath = path.join(requestsDir, `${formRequestClass}.php`);
      ensureDir(requestsDir);
      fs.writeFileSync(requestPath, requestContent, "utf8");
      generatedFiles.push(requestPath);
    }

    // Generate controller
    const controllerContent = generateControllerClass(className, endpoint, formRequestClass, rule);
    const controllerPath = path.join(controllersDir, `${className}.php`);
    fs.writeFileSync(controllerPath, controllerContent, "utf8");
    generatedFiles.push(controllerPath);

    // Route line with path params converted to Laravel syntax
    const laravelPath = endpoint.path.replace(/\{(\w+)\}/g, "{$1}");
    routeLines.push(
      `Route::${endpoint.method}('${laravelPath}', \\App\\Http\\Controllers\\Generated\\${className}::class);`,
    );
  }

  const routesFilePath = path.join(routesDir, "api.php");
  fs.writeFileSync(routesFilePath, routeLines.join("\n") + "\n", "utf8");
  generatedFiles.push(routesFilePath);

  return generatedFiles;
}
