import fs from "node:fs";
import path from "node:path";
import type { ApiContract } from "../types.js";

function toStudly(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]/)
    .filter(Boolean)
    .map((segment) => segment[0].toUpperCase() + segment.slice(1).toLowerCase())
    .join("");
}

function ensureDir(dirPath: string): void {
  fs.mkdirSync(dirPath, { recursive: true });
}

export function generateLaravelFromContract(contract: ApiContract, outPath: string): string[] {
  const generatedFiles: string[] = [];
  const controllersDir = path.join(outPath, "app", "Http", "Controllers", "Generated");
  const routesDir = path.join(outPath, "routes");

  ensureDir(controllersDir);
  ensureDir(routesDir);

  const routeLines: string[] = [
    "<?php",
    "",
    "use Illuminate\\Support\\Facades\\Route;",
    "",
  ];

  for (const endpoint of contract.endpoints) {
    const className = `${toStudly(endpoint.operationId)}Controller`;
    const controllerPath = path.join(controllersDir, `${className}.php`);
    const summaryComment = endpoint.summary ? ` * ${endpoint.summary}\n` : "";

    const controllerContent = `<?php

namespace App\\Http\\Controllers\\Generated;

use Illuminate\\Http\\JsonResponse;
use Illuminate\\Http\\Request;

class ${className}
{
    /**
${summaryComment}     * Auto-generated by BackendBridge.
     */
    public function __invoke(Request $request): JsonResponse
    {
        return response()->json([
            'status' => 'ok',
            'operation' => '${endpoint.operationId}',
            'method' => '${endpoint.method.toUpperCase()}',
            'path' => '${endpoint.path}',
        ]);
    }
}
`;

    fs.writeFileSync(controllerPath, controllerContent, "utf8");
    generatedFiles.push(controllerPath);

    routeLines.push(
      `Route::${endpoint.method}('${endpoint.path}', \\App\\Http\\Controllers\\Generated\\${className}::class);`,
    );
  }

  const routesFilePath = path.join(routesDir, "api.php");
  fs.writeFileSync(routesFilePath, `${routeLines.join("\n")}\n`, "utf8");
  generatedFiles.push(routesFilePath);

  return generatedFiles;
}
