import fs from "node:fs";
import path from "node:path";
import { resolveRule, type MappingDocument } from "../mapping.js";
import type { ApiContract } from "../types.js";
import { toStudly, ensureDir } from "../utils.js";

export function generateSymfonyFromContract(
  contract: ApiContract,
  outPath: string,
  mapping?: MappingDocument,
): string[] {
  const generatedFiles: string[] = [];
  const controllersDir = path.join(outPath, "src", "Controller", "Generated");
  ensureDir(controllersDir);

  for (const endpoint of contract.endpoints) {
    const className = `${toStudly(endpoint.operationId)}Controller`;
    const methodName = toStudly(endpoint.method.toLowerCase()) + toStudly(endpoint.operationId);
    const filePath = path.join(controllersDir, `${className}.php`);
    const summaryComment = endpoint.summary ? ` * ${endpoint.summary}\n` : "";
    const rule = resolveRule(mapping, endpoint.method, endpoint.path, endpoint.operationId);
    const mappingHints = [
      rule?.dto ? ` * DTO: ${rule.dto}` : undefined,
      rule?.validation?.length ? ` * Validation: ${rule.validation.join(", ")}` : undefined,
      rule?.auth?.length ? ` * Auth: ${rule.auth.join(", ")}` : undefined,
      rule?.notes ? ` * Notes: ${rule.notes}` : undefined,
    ]
      .filter(Boolean)
      .join("\n");

    const controllerContent = `<?php

namespace App\\Controller\\Generated;

use Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController;
use Symfony\\Component\\HttpFoundation\\JsonResponse;
use Symfony\\Component\\Routing\\Annotation\\Route;

class ${className} extends AbstractController
{
    /**
${summaryComment}     * Auto-generated by BackendBridge.
${mappingHints ? `${mappingHints}\n` : ""}     */
    #[Route('${endpoint.path}', name: '${endpoint.operationId}', methods: ['${endpoint.method.toUpperCase()}'])]
    public function ${methodName}(): JsonResponse
    {
      ${rule?.auth?.length ? `// Authorization hints: ${rule?.auth?.join(", ")}
      // Example: $this->denyAccessUnlessGranted('VIEW', $resource);
  ` : ""}
      return $this->json([
        'status' => 'ok',
        'operation' => '${endpoint.operationId}',
        'method' => '${endpoint.method.toUpperCase()}',
        'path' => '${endpoint.path}',
      ]);
    }
}
`;

    fs.writeFileSync(filePath, controllerContent, "utf8");
    generatedFiles.push(filePath);
  }

  return generatedFiles;
}
