import fs from "node:fs";
import path from "node:path";
import type { ApiContract } from "../types.js";

function toStudly(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]/)
    .filter(Boolean)
    .map((segment) => segment[0].toUpperCase() + segment.slice(1).toLowerCase())
    .join("");
}

function ensureDir(dirPath: string): void {
  fs.mkdirSync(dirPath, { recursive: true });
}

export function generateSymfonyFromContract(contract: ApiContract, outPath: string): string[] {
  const generatedFiles: string[] = [];
  const controllersDir = path.join(outPath, "src", "Controller", "Generated");
  ensureDir(controllersDir);

  for (const endpoint of contract.endpoints) {
    const className = `${toStudly(endpoint.operationId)}Controller`;
    const methodName = toStudly(endpoint.method.toLowerCase()) + toStudly(endpoint.operationId);
    const filePath = path.join(controllersDir, `${className}.php`);
    const summaryComment = endpoint.summary ? ` * ${endpoint.summary}\n` : "";

    const controllerContent = `<?php

namespace App\\Controller\\Generated;

use Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController;
use Symfony\\Component\\HttpFoundation\\JsonResponse;
use Symfony\\Component\\Routing\\Annotation\\Route;

class ${className} extends AbstractController
{
    /**
${summaryComment}     * Auto-generated by BackendBridge.
     */
    #[Route('${endpoint.path}', name: '${endpoint.operationId}', methods: ['${endpoint.method.toUpperCase()}'])]
    public function ${methodName}(): JsonResponse
    {
        return $this->json([
            'status' => 'ok',
            'operation' => '${endpoint.operationId}',
            'method' => '${endpoint.method.toUpperCase()}',
            'path' => '${endpoint.path}',
        ]);
    }
}
`;

    fs.writeFileSync(filePath, controllerContent, "utf8");
    generatedFiles.push(filePath);
  }

  return generatedFiles;
}
