import fs from "node:fs";
import path from "node:path";
import type { ApiContract } from "../types.js";
import { toStudly, toSnake, ensureDir } from "../utils.js";

function inferResources(contract: ApiContract): string[] {
  const seen = new Set<string>();
  for (const ep of contract.endpoints) {
    const name = ep.tags?.[0] ? toStudly(ep.tags[0]) : toStudly(ep.operationId);
    if (name) seen.add(name);
  }
  return [...seen];
}

// ─── Laravel lang files ───────────────────────────────────────────────────────

function laravelLangFile(resource: string, locale: "en" | "fr"): string {
  const snake = toSnake(resource);
  const labels: Record<"en" | "fr", Record<string, string>> = {
    en: {
      singular: resource,
      plural: `${resource}s`,
      created: `${resource} created successfully.`,
      updated: `${resource} updated successfully.`,
      deleted: `${resource} deleted successfully.`,
      not_found: `${resource} not found.`,
      validation_failed: "Validation failed.",
      unauthorized: "Unauthorized.",
      forbidden: "Forbidden.",
    },
    fr: {
      singular: resource,
      plural: `${resource}s`,
      created: `${resource} créé(e) avec succès.`,
      updated: `${resource} mis(e) à jour avec succès.`,
      deleted: `${resource} supprimé(e) avec succès.`,
      not_found: `${resource} introuvable.`,
      validation_failed: "Validation échouée.",
      unauthorized: "Non authentifié.",
      forbidden: "Accès refusé.",
    },
  };

  const entries = Object.entries(labels[locale])
    .map(([k, v]) => `    '${k}' => '${v}',`)
    .join("\n");

  return `<?php

return [
${entries}
];
`;
}

function laravelValidationLangFile(locale: "en" | "fr"): string {
  const lines: Record<"en" | "fr", string[]> = {
    en: [
      "    'required'   => 'The :attribute field is required.',",
      "    'string'     => 'The :attribute must be a string.',",
      "    'integer'    => 'The :attribute must be an integer.',",
      "    'email'      => 'The :attribute must be a valid email address.',",
      "    'min'        => ['string' => 'The :attribute must be at least :min characters.', 'numeric' => 'The :attribute must be at least :min.'],",
      "    'max'        => ['string' => 'The :attribute may not be greater than :max characters.', 'numeric' => 'The :attribute may not be greater than :max.'],",
      "    'unique'     => 'The :attribute has already been taken.',",
      "    'exists'     => 'The selected :attribute is invalid.',",
    ],
    fr: [
      "    'required'   => 'Le champ :attribute est obligatoire.',",
      "    'string'     => 'Le champ :attribute doit être une chaîne de caractères.',",
      "    'integer'    => 'Le champ :attribute doit être un entier.',",
      "    'email'      => 'Le champ :attribute doit être une adresse e-mail valide.',",
      "    'min'        => ['string' => 'Le champ :attribute doit contenir au moins :min caractères.', 'numeric' => 'Le champ :attribute doit être au minimum :min.'],",
      "    'max'        => ['string' => 'Le champ :attribute ne doit pas dépasser :max caractères.', 'numeric' => 'Le champ :attribute ne doit pas dépasser :max.'],",
      "    'unique'     => 'Ce :attribute est déjà pris.',",
      "    'exists'     => 'Le :attribute sélectionné est invalide.',",
    ],
  };

  return `<?php

return [\n${lines[locale].join("\n")}\n];\n`;
}

export function generateLaravelTranslations(contract: ApiContract, outPath: string): string[] {
  const resources = inferResources(contract);
  const generated: string[] = [];

  for (const locale of ["en", "fr"] as const) {
    const langDir = path.join(outPath, "lang", locale);
    ensureDir(langDir);

    const validationPath = path.join(langDir, "validation.php");
    fs.writeFileSync(validationPath, laravelValidationLangFile(locale), "utf8");
    generated.push(validationPath);

    for (const resource of resources) {
      const snake = toSnake(resource);
      const filePath = path.join(langDir, `${snake}.php`);
      fs.writeFileSync(filePath, laravelLangFile(resource, locale), "utf8");
      generated.push(filePath);
    }
  }

  return generated;
}

// ─── Symfony translations ─────────────────────────────────────────────────────

function symfonyMessagesYaml(resources: string[], locale: "en" | "fr"): string {
  const lines: string[] = [
    `# Symfony translations — ${locale} — generated by BackendBridge`,
    `# Place in translations/messages.${locale}.yaml`,
    "",
  ];

  const labels: Record<"en" | "fr", (r: string) => Record<string, string>> = {
    en: (r) => ({
      [`${toSnake(r)}.created`]: `${r} created successfully.`,
      [`${toSnake(r)}.updated`]: `${r} updated successfully.`,
      [`${toSnake(r)}.deleted`]: `${r} deleted successfully.`,
      [`${toSnake(r)}.not_found`]: `${r} not found.`,
      [`${toSnake(r)}.unauthorized`]: "Unauthorized.",
      [`${toSnake(r)}.forbidden`]: "Forbidden.",
    }),
    fr: (r) => ({
      [`${toSnake(r)}.created`]: `${r} créé(e) avec succès.`,
      [`${toSnake(r)}.updated`]: `${r} mis(e) à jour avec succès.`,
      [`${toSnake(r)}.deleted`]: `${r} supprimé(e) avec succès.`,
      [`${toSnake(r)}.not_found`]: `${r} introuvable.`,
      [`${toSnake(r)}.unauthorized`]: "Non authentifié.",
      [`${toSnake(r)}.forbidden`]: "Accès refusé.",
    }),
  };

  for (const resource of resources) {
    lines.push(`# ${resource}`);
    for (const [key, value] of Object.entries(labels[locale](resource))) {
      lines.push(`'${key}': '${value}'`);
    }
    lines.push("");
  }

  lines.push("# Validation");
  if (locale === "en") {
    lines.push("'error.validation': 'Validation failed.'");
    lines.push("'error.server': 'An unexpected error occurred.'");
    lines.push("'error.not_found': 'Resource not found.'");
  } else {
    lines.push("'error.validation': 'Validation échouée.'");
    lines.push("'error.server': 'Une erreur inattendue est survenue.'");
    lines.push("'error.not_found': 'Ressource introuvable.'");
  }

  return lines.join("\n") + "\n";
}

export function generateSymfonyTranslations(contract: ApiContract, outPath: string): string[] {
  const resources = inferResources(contract);
  const generated: string[] = [];
  const dir = path.join(outPath, "translations");
  ensureDir(dir);

  for (const locale of ["en", "fr"] as const) {
    const filePath = path.join(dir, `messages.${locale}.yaml`);
    fs.writeFileSync(filePath, symfonyMessagesYaml(resources, locale), "utf8");
    generated.push(filePath);
  }

  return generated;
}
