// Auto-generated by scripts/package.mjs — do not edit
export const parseApiPlatform = `<?php
// Robust PHP helper using nikic/php-parser to extract ApiPlatform operations.
// Requires: run \`composer install\` in the tools/ directory first.
// Usage: php parse_api_platform.php /path/to/FileOrDir.php

$cwd = __DIR__;
$autoload = $cwd . '/vendor/autoload.php';
if (!file_exists($autoload)) {
    echo json_encode(["error" => "composer_autoload_missing", "message" => "Run 'composer install' in tools/ directory to install nikic/php-parser."]);
    exit(0);
}

require $autoload;

use PhpParser\\ParserFactory;
use PhpParser\\Node;
use PhpParser\\NodeTraverser;
use PhpParser\\NodeVisitorAbstract;

if ($argc < 2) {
    echo json_encode([]);
    exit(0);
}

$path = $argv[1];

$files = [];
if (is_dir($path)) {
    $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path));
    foreach ($it as $f) {
        if ($f->isFile() && strtolower($f->getExtension()) === 'php') $files[] = $f->getPathname();
    }
} else if (is_file($path)) {
    $files[] = $path;
} else {
    echo json_encode([]);
    exit(0);
}

$parser = (new ParserFactory())->create(ParserFactory::PREFER_PHP7);
$results = [];

foreach ($files as $file) {
    $code = @file_get_contents($file);
    if ($code === false) continue;
    try {
        $ast = $parser->parse($code);
    } catch (\\PhpParser\\Error $e) {
        continue;
    }

    $traverser = new NodeTraverser();
    $visitor = new class($file, $results) extends NodeVisitorAbstract {
        private $file;
        public $resultsRef;
        public function __construct($file, &$results) {
            $this->file = $file;
            $this->resultsRef = &$results;
        }

        private function recordOp($method, $path, $opName) {
            $this->resultsRef[] = [
                'method' => strtolower($method),
                'path' => $path,
                'operationId' => $opName ?: strtolower($method) . '_' . preg_replace('/[^a-z0-9_]+/i', '_', basename($this->file)),
            ];
        }

        public function enterNode(Node $node) {
            // Look for attribute usages like #[Get(uriTemplate: "/...")]
            if ($node instanceof Node\\Stmt\\Class_) {
                foreach ($node->attrGroups as $ag) {
                    foreach ($ag->attrs as $attr) {
                        $name = $attr->name->toString();
                        if (stripos($name, 'ApiResource') !== false) {
                            // check args for 'operations' => array of new Get/Post
                            foreach ($attr->args as $arg) {
                                if ($arg->name && $arg->name->toString() === 'operations' && $arg->value instanceof Node\\Expr\\Array_) {
                                    foreach ($arg->value->items as $item) {
                                        if ($item && $item->value instanceof Node\\Expr\\New_) {
                                            $classNode = $item->value->class;
                                            $short = is_object($classNode) ? $classNode->toString() : (string)$classNode;
                                            $method = $this->guessMethodFromName($short);
                                            $path = $this->findUriInArgs($item->value->args) ?: '/resource';
                                            $this->recordOp($method, $path, null);
                                        }
                                    }
                                }
                            }
                        }
                        // Attributes directly named Get/Post on class
                        if (preg_match('/Get|Post|Put|Patch|Delete/i', $name)) {
                            $method = $this->guessMethodFromName($name);
                            $path = $this->findUriInArgs($attr->args) ?: '/resource';
                            $this->recordOp($method, $path, null);
                        }
                    }
                }
            }

            // New expressions like new Get(...)
            if ($node instanceof Node\\Expr\\New_) {
                $classNode = $node->class;
                $short = is_object($classNode) ? $classNode->toString() : (string)$classNode;
                if (preg_match('/Get|Post|Put|Patch|Delete/i', $short)) {
                    $method = $this->guessMethodFromName($short);
                    $path = $this->findUriInArgs($node->args) ?: '/resource';
                    $this->recordOp($method, $path, null);
                }
            }
        }

        private function guessMethodFromName($name) {
            $n = strtolower($name);
            if (strpos($n, 'post') !== false) return 'post';
            if (strpos($n, 'put') !== false) return 'put';
            if (strpos($n, 'patch') !== false) return 'patch';
            if (strpos($n, 'delete') !== false) return 'delete';
            return 'get';
        }

        private function findUriInArgs($args) {
            foreach ($args as $a) {
                if ($a->name && $a->name->toString() === 'uriTemplate') {
                    if ($a->value instanceof Node\\Scalar\\String_) return $a->value->value;
                }
                // support first string arg
                if (!$a->name && $a->value instanceof Node\\Scalar\\String_) return $a->value->value;
            }
            return null;
        }
    };

    $traverser->addVisitor($visitor);
    $traverser->traverse($ast ?: []);
    // merge results collected by visitor
    if (!empty($visitor->resultsRef)) {
        foreach ($visitor->resultsRef as $r) $results[] = $r;
    }
}

echo json_encode($results);

?>
`;

export const parsePhpClasses = `<?php
// Parse PHP classes and properties using nikic/php-parser
// Usage: php parse_php_classes.php /path/to/file-or-dir.php

$cwd = __DIR__;
$autoload = $cwd . '/vendor/autoload.php';
if (!file_exists($autoload)) {
    echo json_encode(["error" => "composer_autoload_missing", "message" => "Run 'composer install' in tools/ directory to install nikic/php-parser."]);
    exit(0);
}

require $autoload;

use PhpParser\\ParserFactory;
use PhpParser\\Node;
use PhpParser\\NodeTraverser;
use PhpParser\\NodeVisitorAbstract;

if ($argc < 2) {
    echo json_encode([]);
    exit(0);
}

$path = $argv[1];

$files = [];
if (is_dir($path)) {
    $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path));
    foreach ($it as $f) {
        if ($f->isFile() && strtolower($f->getExtension()) === 'php') $files[] = $f->getPathname();
    }
} else if (is_file($path)) {
    $files[] = $path;
} else {
    echo json_encode([]);
    exit(0);
}

$parser = (new ParserFactory())->create(ParserFactory::PREFER_PHP7);
$results = [];

foreach ($files as $file) {
    $code = @file_get_contents($file);
    if ($code === false) continue;
    try {
        $ast = $parser->parse($code);
    } catch (\\PhpParser\\Error $e) {
        continue;
    }

    $traverser = new NodeTraverser();
    $visitor = new class($file, $results) extends NodeVisitorAbstract {
        private $file;
        public $resultsRef;
        public function __construct($file, &$results) {
            $this->file = $file;
            $this->resultsRef = &$results;
        }

        public function enterNode(Node $node) {
            if ($node instanceof Node\\Stmt\\Class_) {
                $className = ($node->namespacedName ? $node->namespacedName->toString() : null) ?? ($node->name ? $node->name->toString() : basename($this->file));
                $props = [];
                foreach ($node->getProperties() as $p) {
                    foreach ($p->props as $pd) {
                            $name = $pd->name->toString();
                            $type = null;
                            $relation = null;
                            if ($p->type) {
                                $type = is_object($p->type) ? $p->type->toString() : (string)$p->type;
                            } else {
                                // try phpdoc
                                $doc = $p->getDocComment();
                                if ($doc) {
                                    if (preg_match('/@var\\s+([A-Za-z0-9_\\\\\\[\\]]+)/', $doc->getText(), $m)) {
                                        $type = $m[1];
                                    }
                                    // detect ORM relation annotations in docblock
                                    if (preg_match('/@ORM\\\\\\\\(ManyToOne|OneToMany|OneToOne|ManyToMany)\\\\(([^)]*)\\)/', $doc->getText(), $rm)) {
                                        $relType = $rm[1];
                                        $args = $rm[2];
                                        $target = null; $mappedBy = null; $inversedBy = null;
                                        if (preg_match('/targetEntity\\s*=\\s*"?\\\\?([A-Za-z0-9_\\\\\\\\]+)"?/', $args, $t)) $target = $t[1];
                                        if (preg_match('/mappedBy\\s*=\\s*"?([A-Za-z0-9_]+)"?/', $args, $m2)) $mappedBy = $m2[1];
                                        if (preg_match('/inversedBy\\s*=\\s*"?([A-Za-z0-9_]+)"?/', $args, $m3)) $inversedBy = $m3[1];
                                        $cascade = null; $orphanRemoval = null;
                                        if (preg_match('/cascade\\s*=\\s*\\{([^}]*)\\}/', $args, $c)) {
                                            $items = array_map('trim', explode(',', $c[1]));
                                            $items = array_map(function($s){ return trim($s, " \\"'"); }, $items);
                                            $cascade = $items;
                                        } else if (preg_match('/cascade\\s*=\\s*(\\w+)/', $args, $c2)) {
                                            $cascade = [trim($c2[1], " \\"'")];
                                        }
                                        if (preg_match('/orphanRemoval\\s*=\\s*(true|false)/i', $args, $or)) {
                                            $orphanRemoval = strtolower($or[1]) === 'true';
                                        }
                                        $relation = ['type'=>$relType, 'target'=>$target, 'mappedBy'=>$mappedBy, 'inversedBy'=>$inversedBy, 'cascade'=>$cascade, 'orphanRemoval'=>$orphanRemoval];
                                    }
                                    // detect Column metadata
                                    if (preg_match('/@ORM\\\\\\\\Column\\(([^)]*)\\)/', $doc->getText(), $cm)) {
                                        $colArgs = $cm[1];
                                        $colType = null; $colLength = null; $colNullable = false; $colUnique = false; $colDefault = null; $colIndex = false;
                                        if (preg_match('/type\\s*=\\s*"?([a-zA-Z0-9_]+)"?/', $colArgs, $t)) $colType = $t[1];
                                        if (preg_match('/length\\s*=\\s*([0-9]+)/', $colArgs, $l)) $colLength = intval($l[1]);
                                        if (preg_match('/nullable\\s*=\\s*(true|false)/i', $colArgs, $n)) $colNullable = strtolower($n[1]) === 'true';
                                        if (preg_match('/unique\\s*=\\s*(true|false)/i', $colArgs, $u)) $colUnique = strtolower($u[1]) === 'true';
                                        // options default patterns: options={"default"=...} or options={"default":"..."}
                                        if (preg_match('/default\\s*[:=]\\s*"([^"]*)"/', $colArgs, $d1)) $colDefault = $d1[1];
                                        else if (preg_match('/default\\s*[:=]\\s*([^,\\)\\s]+)/', $colArgs, $d2)) $colDefault = $d2[1];
                                        // simple index detection
                                        if (preg_match('/@ORM\\\\\\\\Index\\(/', $doc->getText()) || preg_match('/@index/i', $doc->getText())) $colIndex = true;
                                        $column = ['type'=>$colType, 'length'=>$colLength, 'nullable'=>$colNullable, 'unique'=>$colUnique, 'default'=>$colDefault, 'index'=>$colIndex];
                                    } else {
                                        $column = null;
                                    }
                                }
                            else {
                                $column = null;
                            }
                            }
                            // also check PHP 8 attributes on the property
                            if (!$relation && !empty($p->attrGroups)) {
                                foreach ($p->attrGroups as $ag) {
                                    foreach ($ag->attrs as $attr) {
                                        $nameStr = is_object($attr->name) ? $attr->name->toString() : (string)$attr->name;
                                        if (preg_match('/ManyToOne|OneToMany|OneToOne|ManyToMany/i', $nameStr, $mm)) {
                                            $relType = $mm[0];
                                            // get args
                                            $argsText = '';
                                            foreach ($attr->args as $a) {
                                                if ($a->name) {
                                                    $argsText .= $a->name->toString() . '=';
                                                }
                                                if ($a->value instanceof Node\\Scalar\\String_) $argsText .= $a->value->value . ',';
                                            }
                                            $target = null; $mappedBy = null; $inversedBy = null;
                                            if (preg_match('/targetEntity=.*?([A-Za-z0-9_\\\\\\\\]+)/', $argsText, $t)) $target = $t[1];
                                            $relation = ['type'=>$relType, 'target'=>$target, 'mappedBy'=>$mappedBy, 'inversedBy'=>$inversedBy];
                                        }
                                    }
                                }
                            }
                            $props[] = ['name' => $name, 'type' => $type, 'relation' => $relation, 'column' => isset($column) ? $column : null];
                        }
                }
                $this->resultsRef[] = ['file' => $this->file, 'class' => $className, 'properties' => $props];
            }
        }
    };

    $traverser->addVisitor($visitor);
    $traverser->traverse($ast ?: []);
    if (!empty($visitor->resultsRef)) {
        foreach ($visitor->resultsRef as $r) $results[] = $r;
    }
}

echo json_encode($results);

?>`;
export const parseControllers = `<?php
// Parse Symfony controllers and Laravel route files using nikic/php-parser.
// Returns JSON array of { method, path, operationId, tags, pathParams }.
// Usage:
//   php parse_controllers.php symfony /path/to/src/Controller
//   php parse_controllers.php laravel /path/to/routes/api.php

$cwd = __DIR__;
$autoload = $cwd . '/vendor/autoload.php';
if (!file_exists($autoload)) {
    echo json_encode(["error" => "composer_autoload_missing"]);
    exit(0);
}

require $autoload;

use PhpParser\\ParserFactory;
use PhpParser\\Node;
use PhpParser\\NodeTraverser;
use PhpParser\\NodeVisitorAbstract;

if ($argc < 3) {
    echo json_encode([]);
    exit(0);
}

$framework = strtolower($argv[1]);
$targetPath = $argv[2];

$parser = (new ParserFactory())->create(ParserFactory::PREFER_PHP7);

// ─── Helpers ──────────────────────────────────────────────────────────────────

function normalizePath(string $p): string {
    return str_starts_with($p, '/') ? $p : '/' . $p;
}

function pathParamsFrom(string $path): array {
    preg_match_all('/\\{(\\w+)\\??\\}/', $path, $m);
    return $m[1];
}

function tagFromPath(string $path, string $fallback): string {
    $segs = array_filter(explode('/', $path), fn($s) => $s !== '' && !str_starts_with($s, '{'));
    $first = reset($segs);
    return $first ? ucfirst($first) : $fallback;
}

function collectFiles(string $path): array {
    if (is_file($path)) return [$path];
    if (!is_dir($path)) return [];
    $result = [];
    $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path));
    foreach ($it as $f) {
        if ($f->isFile() && strtolower($f->getExtension()) === 'php') $result[] = $f->getPathname();
    }
    return $result;
}

function getAttrArgs(Node\\Attribute $attr): array {
    $args = [];
    foreach ($attr->args as $arg) {
        $key = $arg->name ? $arg->name->toString() : null;
        $val = null;
        if ($arg->value instanceof Node\\Scalar\\String_) {
            $val = $arg->value->value;
        } elseif ($arg->value instanceof Node\\Expr\\Array_) {
            $items = [];
            foreach ($arg->value->items as $item) {
                if ($item && $item->value instanceof Node\\Scalar\\String_) {
                    $items[] = $item->value->value;
                }
            }
            $val = $items;
        } elseif ($arg->value instanceof Node\\Expr\\ClassConstFetch) {
            $val = $arg->value->name instanceof Node\\Identifier
                ? $arg->value->name->toString()
                : null;
        }
        if ($key !== null) {
            $args[$key] = $val;
        } elseif ($val !== null) {
            $args[] = $val;
        }
    }
    return $args;
}

// ─── Symfony controller extraction ───────────────────────────────────────────

function extractSymfony(string $path, $parser): array {
    $endpoints = [];
    foreach (collectFiles($path) as $file) {
        if (!str_contains($file, 'Controller')) continue;
        $code = @file_get_contents($file);
        if (!$code) continue;
        try { $ast = $parser->parse($code); } catch (\\PhpParser\\Error $e) { continue; }
        if (!$ast) continue;

        // Find class-level Route prefix
        $classPrefix = '';
        $classTag    = 'Api';
        foreach ($ast as $node) {
            if (!($node instanceof Node\\Stmt\\Namespace_)) continue;
            foreach ($node->stmts as $stmt) {
                if (!($stmt instanceof Node\\Stmt\\Class_)) continue;

                // Class-level #[Route] prefix
                foreach ($stmt->attrGroups as $ag) {
                    foreach ($ag->attrs as $attr) {
                        if (!in_array($attr->name->toString(), ['Route', 'Symfony\\\\Component\\\\Routing\\\\Attribute\\\\Route'])) continue;
                        $args = getAttrArgs($attr);
                        $classPrefix = $args['path'] ?? $args[0] ?? '';
                        $classTag    = tagFromPath($classPrefix ?: '/api', basename($file, 'Controller.php'));
                    }
                }

                // Method-level #[Route]
                foreach ($stmt->getMethods() as $method) {
                    if ($method->isAbstract() || !$method->isPublic()) continue;
                    foreach ($method->attrGroups as $ag) {
                        foreach ($ag->attrs as $attr) {
                            if (!in_array($attr->name->toString(), ['Route', 'Symfony\\\\Component\\\\Routing\\\\Attribute\\\\Route'])) continue;
                            $args    = getAttrArgs($attr);
                            $subPath = $args['path'] ?? $args[0] ?? '';
                            $name    = $args['name'] ?? null;
                            $methods = (array)($args['methods'] ?? ['GET']);
                            $full    = normalizePath(rtrim($classPrefix, '/') . '/' . ltrim($subPath, '/'));
                            $full    = preg_replace('#/+#', '/', $full);
                            foreach ($methods as $m) {
                                $m = strtolower($m);
                                $endpoints[] = [
                                    'method'      => $m,
                                    'path'        => $full,
                                    'operationId' => $name ?? "{$m}_" . preg_replace('/[^a-z0-9]+/', '_', trim($full, '/')),
                                    'tags'        => [$classTag],
                                    'pathParams'  => pathParamsFrom($full),
                                ];
                            }
                        }
                    }
                }
            }
        }
    }
    return $endpoints;
}

// ─── Laravel route file extraction ───────────────────────────────────────────

function extractLaravel(string $path, $parser): array {
    $endpoints = [];
    $files = is_dir($path)
        ? array_merge(
            is_file("$path/api.php")   ? ["$path/api.php"] : [],
            is_file("$path/web.php")   ? ["$path/web.php"] : [],
            collectFiles($path)
          )
        : [$path];

    foreach (array_unique($files) as $file) {
        if (!file_exists($file)) continue;
        $code = @file_get_contents($file);
        if (!$code) continue;
        try { $ast = $parser->parse($code); } catch (\\PhpParser\\Error $e) { continue; }
        if (!$ast) continue;

        $traverser = new NodeTraverser();
        $visitor   = new class($endpoints) extends NodeVisitorAbstract {
            public array $endpoints;
            public function __construct(array &$endpoints) { $this->endpoints = &$endpoints; }

            private function getString(Node\\Expr $node): ?string {
                return $node instanceof Node\\Scalar\\String_ ? $node->value : null;
            }

            public function enterNode(Node $node) {
                if (!($node instanceof Node\\Expr\\StaticCall)) return;
                if (!($node->class instanceof Node\\Name) || $node->class->toString() !== 'Route') return;
                $method = strtolower($node->name instanceof Node\\Identifier ? $node->name->toString() : '');

                $httpMethods = ['get','post','put','patch','delete','head','options'];
                if (in_array($method, $httpMethods) && isset($node->args[0])) {
                    $rawPath = $this->getString($node->args[0]->value);
                    if (!$rawPath) return;
                    $path = '/' . ltrim($rawPath, '/');
                    $tag  = tagFromPath($path, 'Api');
                    $this->endpoints[] = [
                        'method'      => $method,
                        'path'        => $path,
                        'operationId' => "{$method}_" . preg_replace('/[^a-z0-9]+/', '_', trim($path, '/')),
                        'tags'        => [$tag],
                        'pathParams'  => pathParamsFrom($path),
                    ];
                } elseif (in_array($method, ['resource', 'apiresource']) && isset($node->args[0])) {
                    $rawRes = $this->getString($node->args[0]->value);
                    if (!$rawRes) return;
                    $base = '/' . ltrim($rawRes, '/');
                    $tag  = tagFromPath($base, ucfirst($rawRes));
                    $routes = [
                        ['get',    $base,           "index_{$rawRes}"],
                        ['post',   $base,           "store_{$rawRes}"],
                        ['get',    "$base/{id}",    "show_{$rawRes}"],
                        ['put',    "$base/{id}",    "update_{$rawRes}"],
                        ['delete', "$base/{id}",    "destroy_{$rawRes}"],
                    ];
                    foreach ($routes as [$m, $p, $opId]) {
                        $this->endpoints[] = [
                            'method'      => $m,
                            'path'        => $p,
                            'operationId' => $opId,
                            'tags'        => [$tag],
                            'pathParams'  => pathParamsFrom($p),
                        ];
                    }
                }
            }
        };
        $traverser->addVisitor($visitor);
        $traverser->traverse($ast);
    }
    return $endpoints;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

$results = match($framework) {
    'symfony' => extractSymfony($targetPath, $parser),
    'laravel' => extractLaravel($targetPath, $parser),
    default   => [],
};

// Deduplicate by method+path
$seen = [];
$dedup = [];
foreach ($results as $r) {
    $key = $r['method'] . ':' . $r['path'];
    if (!isset($seen[$key])) {
        $seen[$key] = true;
        $dedup[] = $r;
    }
}

echo json_encode($dedup, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);`;
